[package]
name = "day8"
version = "0.1.0"
authors = ["Frerich Raabe <frerich.raabe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools="0.8.2"
